---
title: "indicators"
author: "Leandro Jimenez"
date: "2 de maio de 2016"
output: html_document
runtime: shiny
---

## Course Project: Shiny Application and Reproducible Pitch

This is the final presentation for the Course Project of the "Developing data products" course
This course is part of the "Data Science specialization"
The project consists in two activities:
Create a Shiny application
Create a presentation in Slidify or Rstudio Presenter to pitch for the application.

# overview


This was built as part of a deliverable for the course Developing Data Products as part of the Coursera Data Science Specialization.

Source code for ui.R and server.R files are available on the GitHub repo: https://github.com/jleandroj/indicators

take at look in the aplications https://indicators.shinyapps.io/indicators/

# about indicators aplication: 

I have used gapminder dataset

Global indicators are the objective of gapminder. This site allows us about economic and social indicators of most countries around the world. More information about gapminder click [here](https://www.gapminder.org).

Application: 

In this aplication you can see your country and compare whit others about some important subjects such as income per person or alcohol comsumption.

you can see all data about your country looking for any indicator that you want to see using search option.

More information about Description of Indicators please to go read.rmd file in https://github.com/jleandroj/indicators or about indicators in the aplication in https://indicators.shinyapps.io/indicators/


# indicators

```{r echo=FALSE,warning=FALSE,message=FALSE}
shinyAppDir("C:/Users/Usuario/Desktop/indicators",
  options=list(
    width="100%", height=550
  )
)
```

# Results

The map shows the countries around the world to each indicators.

You can choice the country that you want to see.

Using search we can see data about each country and see the number of 13 indicators

You can https://indicators.shinyapps.io/indicators/
```





